### ISSUE TITLE
Missing exchange code?

### ISSUE THREAD

**Issue by leifen1** [FINDarkside/TLD-Developer-Console#12]
#EOS# Unable to parse the exchange code! We cannot login into the Epic Online Services without it!  The game will now exit!

the log has this line in it

**Comment by ds5678** [comment]
This is most likely completely unrelated to the developer console, other than it logging this game output.

**Comment by maxim4443** [comment]
![image](https://github.com/FINDarkside/TLD-Developer-Console/assets/154433496/bd68e234-cfe8-47cc-9ccc-4cb63f4cad71)
Good afternoon. There is a problem with the "feat_set_enabled" command. After using the command, the icons in the main menu are duplicated (I play on interloper) Please help me what to do with this?

**Comment by ds5678** [comment]
Other than a couple commands, most of them come from Hinterland, including that one.
