### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by LuciousLisa** [FINDarkside/TLD-Developer-Console#14]
Using the latest version of MelonLoader (0.5.4) and version v2.02 (99904) of TLD. Pressing F1 in game does nothing at all.

Edit (after the issue was closed): apparently you have to be in the pause menu to open the console. My bad, that wasn't noted in the README so I didn't know. @FINDarkside FYI

**Comment by ds5678** [comment]
I just checked. Everything is working fine.

**Comment by FINDarkside** [comment]
> Edit (after the issue was closed): apparently you have to be in the pause menu to open the console. My bad, that wasn't noted in the README so I didn't know. @FINDarkside FYI

That shouldn't be the case actually, I actually used the mod yesterday and it worked normally (not in pause menu) with newest TLD version. 🤔
