### ISSUE TITLE
ill2cpp_init detour failed

### ISSUE THREAD

**Issue by nls-thsg** [FINDarkside/TLD-Developer-Console#20]
after installing melon loader  v0.6.0 and putting the new developer console .dll in the mods folder, starting tld returns an internal error "ill2cpp_init detour failed" i suspect i may be an issue with melonloader rather than the mod, but i'd still appreciate any sort of fix y'all might have

**Comment by ds5678** [comment]
Out of our control. Post a Melonloader issue instead.
