### ISSUE TITLE
item decay

### ISSUE THREAD

**Issue by kazykong** [FINDarkside/TLD-Developer-Console#22]
hello, items come with random health in add_all_gear command, is there a solution?

**Comment by ds5678** [comment]
```
add gear_name quantity condition
```

**Comment by kazykong** [comment]
Hello, I wanted to say something else. Even though I wrote things like add_all_gear 1 100, the condition of the items is bad. Is there any other way?

**Comment by ds5678** [comment]
The vast majority of commands are not created by us. They were created by hinterland

**Comment by kazykong** [comment]
Thanks for your help
