### ISSUE TITLE
Is there a way to list all available items or commands?

### ISSUE THREAD

**Issue by akzmonster** [FINDarkside/TLD-Developer-Console#4]
First off, I have to thank you so very much for making this. I can finally play this game without needless grinding. I feel like the developers of this game have a passion for the art but vehemently hate their own patronage.

I used the "help" command which shows a portion of the commands available but it is a very incomplete list. I can't seem to be able to find an exhaustive list of all commands available. At the very least an item name list would be enough. Thanks!

**Comment by akzmonster** [comment]
Okay, after tremendous trial and error I found these:


accelerant
antiseptic
blueflare
cargopants
cloth
coal
cookedmeatdeer
deerskinboots
deerskinpants
downskijacket
flaregun
flaregunammosingle
hardwood
heavybandage
lampfuel
lantern
longunderwear
mittens
prybar
rabbitskinhat
rabbitskinmittens
recycledcan
rifle
rifleammobox
riflecleaningkit
sewingkit
softwood
stick
tinder
toque
water1000ml
woolsocks
woolsweater
workboots
workgloves
workpants

Then I found this which was posted on https://www.moddb.com/mods/umod-tld/downloads/readme9

It's a little outdated but fills in most of the gaps.

Accelerant
AccelerantKerosene
Arrow
ArrowHead
ArrowShaft
BankManagerHouseKey
BankVaultCode
BaseballCap
BasicBoots
BasicGloves
BasicShoes
BasicWinterCoat
BasicWoolHat
BasicWoolScarf
BearEar
BearHide
BearHideDried
BearQuarter
BearSkinBedRoll
BearSkinCoat
BedRoll
BeefJerky
BirchSaplingDried
BottleAntibiotics
BottleHydrogenPeroxide
BottlePainKillers
Bow
BrokenArrow
BrokenRifle
CacheNote_ChurchMarshDir
CandyBar
CannedBeans
CannedSardines
CanOpener
CargoPants
CattailStalk
CaveCacheNote
Charcoal
ClimbingSocks
Cloth
CoffeeCup
CookedCohoSalmon
CookedLakeWhiteFish
CookedMeatBear
CookedMeatDeer
CookedMeatRabbit
CookedMeatWolf
CookedRainbowTrout
CookedSmallMouthBass
CookingPot
CottonHoodie
CottonScarf
CottonShirt
CottonSocks
Crackers
CrowFeather
DeerSkinBoots
DeerSkinPants
DogFood
DownSkiJacket
DownVest
EnergyBar
FarmerDepositBoxKey
FixedRifle
FlareA
FlareGun
FlareGunAmmoSingle
Flashlight
FleeceMittens
FleeceSweater
ForestTalkerFlyer
ForestTalkerHiddenItem
ForestTalkerMap
ForestTalkerThankyou
ForestTalkerThankyou2
ForgeBlueprints
GranolaBar
GreyMotherBoots
GreyMotherPearls
GreyMotherTrunkKey
Gut
GutDried
Hammer
HankHatchCode
HankJournal2
HankNeiceLetter
HardCase
Hardwood
Hatchet
HatchetImprovised
HC_EP1_FM_TreeRoots_Dir
HC_EP1_ML_AlansCave_Dir
HC_EP1_ML_ClearCut_Dir
HC_EP1_ML_TracksEnt_Dir
HC_EP1_RW_HunterLodge_Dir
HC_EP1_RW_RavineEnd_Dir
HeavyBandage
HighQualityTools
Hook
HookAndLine
InsulatedVest
Jeans
JeremiahKnife
JeremiahsCoat
Knife
KnifeImprovised
KnifeScrapMetal
LakeTrailerKey1
LeatherDried
LeatherHide
LeatherHideDried
LeatherShoes
LetterBundle
LightParka
Line
LongUnderwear
MapleSaplingDried
MedicalSupplies
MiltonDepositBoxKey1
MiltonDepositBoxKey2
MiltonDepositBoxKey3
Mittens
MooseHideBag
MooseHideCloak
MooseHideDried
MountainTownFarmKey
MRE
Newsprint
NewsprintRoll
OldLadyStolenItem
OldMansBeardDressing
OldMansBeardHarvested
PackMatches
PaperStack
PinnacleCanPeaches
Placeholder
PlaidShirt
Prybar
RabbitCarcass
RabbitPelt
RabbitPeltDried
RabbitSkinMittens
RawCohoSalmon
RawLakeWhiteFish
RawMeatBear
RawMeatDeer
RawMeatRabbit
RawMeatWolf
RawRainbowTrout
RawSmallMouthBass
ReclaimedWoodB
RecycledCan
ReishiMushroom
ReishiPrepared
ReishiTea
Rifle
RifleAmmoBox
RifleAmmoSingle
RifleCleaningKit
RifleHuntingLodge
Rope
RoseHip
RosehipsPrepared
RoseHipTea
ScrapMetal
SewingKit
SharpeningStone
SimpleTools
SkiJacket
Snare
Soda
SodaGrape
SodaOrange
Softwood
StagQuarter
Stick
Stone
TeeShirt
Tinder
Toque
Torch
TrailerSupplies
Water1000ml
Water500ml
WaterPurificationTablets
WaterSupplyNotPotable
WaterSupplyPotable
WillBoots
WillPants
WillParka
WillShirt
WillSweater
WillToque
WolfCarcass
WolfPelt
WolfPeltDried
WolfQuarter
WolfSkinCape
WoodMatches
WoolSocks
WoolSweater
WorkBoots
WorkGloves

**Comment by akzmonster** [comment]
Capitalization doesn't seem to matter much, just precede what you want by "add " and some items can even have a quantity modifier. Like "add stick 12". But others like "add cookedmeatdeer 10" will still only yield 1 at a time. Nevertheless, the game is playable again!

**Comment by FINDarkside** [comment]
I think `help` should list all commands, but you might need to scroll. IIRC scrolling is a bit wonky, but haven't played TLD for a while.

You can also find the item list [here](https://github.com/FINDarkside/TLD-Save-Editor/blob/master/The%20Long%20Dark%20Save%20Editor%202/Helpers/ItemDictionary.cs#L40), and if you want to search by ingame name, you can search for them in  [translation files for the save editor (ctrl+f)](https://github.com/FINDarkside/TLD-Save-Editor/blob/master/The%20Long%20Dark%20Save%20Editor%202/Properties/Resources.resx).

Btw, just in case you weren't aware, tab is autocomplete in the console.
