### ISSUE TITLE
Teleporting to different regions around the map.

### ISSUE THREAD

**Issue by whatisoven** [FINDarkside/TLD-Developer-Console#5]
I wanted to know if you could teleport around the map. I have never seen any commands related to the different regions. I wanted to teleport around the Escape the DarkWalker map but i don't know how.

**Comment by FINDarkside** [comment]
Do you mean teleporting to different region or teleporting within a region? I think there's some kind of teleport command (takes coordinates as argument) but I don't remember how it works.

**Comment by whatisoven** [comment]
Teleporting to a different region.

**Comment by zeobviouslyfakeacc** [comment]
You can use the `scene` command for that purpose. Its only argument is the name of the scene you want to teleport to.
For a list of all scenes, use the `scene_list` command; to get the name of the current scene, use the `scene_name` command.

**Comment by whatisoven** [comment]
Thanks
