### ISSUE TITLE
Are there any commands adding feats to the current survival ?

### ISSUE THREAD

**Issue by CInderss** [FINDarkside/TLD-Developer-Console#6]
Command - "feat_set_enabled" removes all enabled feats , is there a command to enable individual or all in an already existing survival ?

**Comment by ds5678** [comment]
`feat_set_enabled` is indeed the correct command. You just weren't using the correct parameters.

For example:

`feat_set_enabled` disables all feats on that save.

`feat_set_enabled SnowWalker` enables the Snow Walker feat and disables all others.

`feat_set_enabled SnowWalker BlizzardWalker` enables both Snow Walker and Blizzard Walker. It disables all other feats.

Capitalization is important.

Here is the list of current feats:
* `BookSmarts`
* `ColdFusion`
* `EfficientMachine`
* `FireMaster`
* `FreeRunner`
* `SnowWalker`
* `ExpertTrapper`
* `StraightToHeart`
* `BlizzardWalker`
* `NightWalker`

**Comment by CInderss** [comment]
Thank you very much !
