### ISSUE TITLE
Search gear

### ISSUE THREAD

**Issue by RafaelNET** [FINDarkside/TLD-Developer-Console#7]
Is possible add search command to gear items?

for example: typing "search gear box" or "gear_add *box*" would show all gears that contain "box" in the name

Thanks

Great Mod, thank you so much

Rafael Andrade

**Comment by ds5678** [comment]
Pressing tab generates autocomplete results for various commands including `gear_add` and `add`

**Comment by FINDarkside** [comment]
Yeah I think because of tab autocompletion, there's no need for separate search gear command.
